DROP TABLE IF EXISTS POSTS;

CREATE TABLE POSTS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    description VARCHAR(10000) DEFAULT NULL,
    creation_date DATE DEFAULT CURRENT_DATE
);